development:
  adapter: postgresql
  encoding: unicode
  database: billinho_development
  pool: 5
  username: billinho
  password: foobar123

test:
  adapter: postgresql
  encoding: unicode
  database: billinho_test
  pool: 5
  username: billinho
  password: foobar123
