# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 46989f3d6b7a0ee9cf2131c5ae48ad0804f903985c91741f74c20122641a4aff9dbbf1000cb32fbf0f38af18c80c3365dc29496258ce2afe9252db247e0d1f24

test:
  secret_key_base: aa57af710f39352bcb535af8c8623da5382d2a0cfeb94a0530c59c9e2e5557d966f0cd9e7a98f7db0db59de4883bfcbd2d80a63f676a55f7385b320ea044c7a5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
